### ISSUE TITLE
Proposal: manage wallet and sign transaction at front end

### ISSUE THREAD

**Issue by ghost** [witoldsz/semux-light#2]
Is it possible to add wallet management to the font end, so that it work with the server in a decentralized way?

**Comment by witoldsz** [comment]
The wallet management: create new, load from file and import private key are in progress now.
The transaction signing is completed already: it requires to provide a private key.
When wallet management is ready, the "private key" field will be replaced by a source account dropdown.

![image](https://user-images.githubusercontent.com/544581/40149958-2806aab2-5977-11e8-8a00-468acf27344c.png)

**Comment by witoldsz** [comment]
Wallet management is 50% completed:
- you can generate a new wallet and save it as an JSON file (private keys are encrypted)
- you can load a JSON wallet
- TODO: generating a new wallet from private key
- TODO: import private key into JSON wallet

![image](https://user-images.githubusercontent.com/544581/40456614-9f4a3f50-5ef2-11e8-80ba-cd3bd1630c11.png)

![image](https://user-images.githubusercontent.com/544581/40456593-7e6b33a2-5ef2-11e8-8ec4-b27d767d50fc.png)

example `semux-wallet.json`
```json
{
    "version": 1,
    "network": "TESTNET",
    "cipher": {
        "salt": "e9e5defb129ef8828bfbdba9d547b06b",
        "iv": "6606b217ab936f1db70d6f189110d641"
    },
    "accounts": [
        {
            "address": "0xd6562866496d1c43ca2f433ee69f42663f99fa30",
            "encrypted": "1502b48b4dda1e06e130a2f5cd1986f09171593195a0336928d8c3d40821cd224fd2a92b5fbe4cfa0d3073c548e3f4db352d8abd08084d647ca27a8b651de3e7"
        },
        {
            "address": "0x7acb178cfb49b84ae51f79987a8eda1c43b712b0",
            "encrypted": "1502b48b4dda1e06e130a2f5cd1986f00e9a81ea473605e6861dbbacfb1ed311e677c8a16c2cd14025f6ebdc954a3baf60bb5e2426910a3856c3c7cf73651b8c"
        }
    ]
}

```

**Comment by witoldsz** [comment]
Wallet management update: 

![image](https://user-images.githubusercontent.com/544581/40517965-5c18c5c8-5fb8-11e8-8a80-45939dbccf45.png)
