### ISSUE TITLE
Is wallet v3 supported now?

### ISSUE THREAD

**Issue by semuxgo** [witoldsz/semux-light#23]

**Comment by witoldsz** [comment]
You mean, the semux-core official client binary wallet format file?
Semux light uses JSON format, it does not understand the binary format of semux-core wallets.

If you would like, I could take a look at a JSON wallet file for semux-core. It would make working/integration with it easier. What do you think? It could be a little bit a challenge to find exactly the same cryptography libs for both Java and JavaScript, but… it's just a challenge :)

**Comment by witoldsz** [comment]
This is how a `semux-wallet.json` file, for Semux Light, looks like:

```json
{
  "version": 1,
  "network": "MAINNET",
  "cipher": {
    "salt": "702488cbf1ded1afdb32c191297d48cd",
    "iv": "35547e63b15059098eee5a3c39099917"
  },
  "accounts": [
    {
      "address": "0x48837bad3ba829b0edddc061dc35c60b8363fa0e",
      "encrypted": "fd2c3660b18aba4584b05bde2638c4579215b1e93fba6b81becac78bab241d58b93be130b6c862629d5385f1be29647c8db5c72c35c33c248cb3e07a97171bfd"
    }
  ]
}
```

The address book is missing, I am not sure if address book and encrypted account private keys together are OK. One should backup, put private keys in safe place and, on the other hand, the address book is not that sensitive piece of data.

**Comment by witoldsz** [comment]
Please reopen if necessary.
