### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by ghost** [witoldsz/semux-light#3]
Got an `Unexpected end of JSON input` error in the browser.

Semux: `Semux/v1.1.1-a089548/Windows/amd64` 
Network: `Testnet`
Semux light:  2bf2f38566d5518a8faa5d147abda863428784b7

**Comment by witoldsz** [comment]
What are the steps to reproduce it?

**Comment by witoldsz** [comment]
Please reopen if this happens again.
